name: gharelu
description: A new Flutter project.


version: 1.0.0+0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.2
  flutter_svg: ^2.0.3
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^2.0.0-dev.9
  image_cropper: ^3.0.1
  image_picker: ^0.8.5+3
  json_annotation: ^4.4.0
  logger: ^1.1.0
  permission_handler: ^10.0.0
  url_launcher: ^6.1.5
  velocity_x: ^3.5.1
  carousel_slider: ^4.1.1
  chat_bubbles: ^1.3.0
  dartz: ^0.10.1
  flutter_map: ^3.1.0
  dio: ">=4.0.6 <6.0.0"
  dotted_border: ^2.0.0+2
  firebase_storage: ^11.0.10
  calendar_timeline: ^1.0.5
  khalti_flutter: ^2.1.0
  webview_flutter: ^4.0.1
  lottie: ^2.1.0
  awesome_notifications: ^0.7.4+1
  flutter_hooks: ^0.18.5+1
  algolia_helper_flutter: ^0.2.3
  flutter_typeahead: ^4.1.1
  dropdown_button2: ^1.9.2
  flutter_native_splash: ^2.2.16
  get_it: ^7.2.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.1.10
  flutter_gen_runner: ^5.1.0+1
  # flutter_osm_plugin: ^0.37.1
  flutter_launcher_icons: ^0.11.0
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.1

dependency_overrides:
  ? analyzer
  ? meta

flutter_gen:
  output: lib/src/core/assets/
  integrations:
    flutter_svg: true
    lottie: true

flutter:

  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - .env


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/gharelu_logo.jpg"
  min_sdk_android: 21

flutter_native_splash:
  color: '#7210FF'
  image: "assets/images/gharelu_logo.jpg"
